spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_ss?useSSL=false
    username: root
    password: 6352185jt
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0


management:
  security:
    enabled: false

persion:
    name: jintao
    age: 26
    desc: ${persion.name} is writing ${persion.age}

